# Generated by Django 4.2 on 2023-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=50)),
                ('nameOfTable', models.CharField(max_length=50)),
                ('nameOfWaiter', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategoryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainStreamFoodName', models.CharField(max_length=100)),
                ('subCategoryFoodCharge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Waiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WaiterName', models.CharField(max_length=50)),
            ],
        ),
    ]
